<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/07 23:16:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sandbox',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
